bluecmd/fortigate_exporter

- Dockerfile
- README.md
- docker-compose.yml
Changed fortigate-key.yaml to /config instead of /opt so this can be Kubernetes Secret mounted
referenced in https://github.com/bluecmd/fortigate_exporter/issues/12
> changed fortigate-key.yaml to /config

- Dockerfile
This PR splits up the CMD directive in the Dockerfile into an ENTRYPOINT and CMD part. 
This allows a easy overloading of all parameters while fixing the binary to be executed.
> feat(Dockerfile): split up CMD into ENTRYPOINT and CMD

- README.md
- forti_token_client.go
- fortigate_exporter.go
This should help the folks in #14 by providing an easier way to specify
more CAs to trust.
> Add a way to specify extra CAs to be trusted

- fortigate_exporter.go
- probe.go
- probe_test.go
This is a better way to expose metrics that are proxied. Right now we
have counters that are exposed as gauges (#5) as we cannot easily proxy
the counters from the Fortigate API.
This change adds a new way to make probe functions that can easily
expose counter values.
> Prepare for moving metrics to collection

- probe.go
- probe_test.go
This removes the older way of using Registry.MustRegister and Set/Add
constructs of metrics and allows us to construct Counters/Gauges etc
without restrictions.
> probe: refactor to use new metrics return

- README.md
- probe.go
- probe_test.go
This fixes #5. Some metrics have accidentally been set to gauges,
these are now counters.
> retype metrics

- README.md
- probe.go
- probe_test.go
- testdata/link-monitor.jsonnet
Implements the link-monitor API. 
Is needed here to get the jitter of WAN links
> feat: implement link-monitor API

- README.md
- probe.go
- probe_test.go
- testdata/virtual_wan_health_check.jsonnet
First of all the work you've done in this project, what a great concept!
I missed the metrics for monitoring WAN link stats in a SDWAN setup, so I added this.
Mostly a copy of the "fortigate_link" metrics.
API URI **api/v2/monitor/virtual-wan/health-check?vdom=***
``` json
[
{
"http_method": "GET",
"results": {
"Internet Check": {
"WAN1_VL300": {
"status": "up",
"latency": 5.5963668823242188,
"jitter": 0.035966649651527405,
"packet_loss": 0,
"packet_sent": 269554,
"packet_received": 269491,
"sla_targets_met": [],
"session": 516,
"tx_bandwidth": 59800,
"rx_bandwidth": 198690,
"state_changed": 1614107800
}
}
},
"vdom": "root",
"path": "virtual-wan",
"name": "health-check",
"status": "success",
"serial": "FGT60EXXXXXXXXXX",
"version": "v6.4.5",
"build": 1828
}
]
``` 
DOCS:
> {
"path": …
> Added SDWAN/Virtual WAN health monitor

- probe.go
- probe_test.go
- testdata/fw-policy-pre64.jsonnet
- testdata/interface.jsonnet
This PR replaces ints used for parsing with int64 and float64 to prevent that too big numbers are tried to be parsed.     
Further it reduces the parsing steps through signalling the parser to directly parse to float64 instead of parsing it in an extra step. 
I couldn't reproduce the error but this should be IMHO done anyway. 
Context: #56
> feat: use float64 or int64 to prevent errors from too big numbers 

- .releaserc.yml
Closes #67 
Used JSON to YAML tooling to detect the error in the config file. 
I have used this JSON as basis to find this https://github.com/semantic-release/github .     
I confirmed that semver is detecting the plugin configuration locally.
> fix(CI): adapt configuration of semantic to add github artifacts

- README.md
> doc(known-issues): memory leak in 6.2.x

- Dockerfile
This removes our dependency on Docker Hub, as well as fixing our
dependencies at a certain version (1.16.2 in this case).
Fixes #75
> fix(docker): Use Prometheus' Golang Builder

- probe.go
- probe_test.go
- testdata/fw-loadbalancers.jsonnet
Seems Real Server RTT is sometimes reported as an empty value (spotted on our FG unit). Reporting this case immediately as NaN without trying to parse it and generating a log message for it.
> handle empty rtt value without error log msg

- .releaserc.yml
- Makefile
As we had an user requesting to run the fortigate exporter on a RaspberryPi and ARM64 becoming more and more common, I think we should provide ARM64 binaries
https://www.reddit.com/r/fortinet/comments/llwqab/fortigate_exporter_for_prometheus/grt5ipc?utm_source=share&utm_medium=web2x&context=3
> feat(CI): build artifacts for ARM64 on release

- Makefile
This should result in static binaries, and we should not need CGO
anyhow.
Fixes #80
> fea(ci): Disable CGO for building

- probe.go
- probe_test.go
- testdata/ipsec.jsonnet
Currently the exporter will fail if it runs into a IPSec tunnel with multiple phase2 proposals having the same name. 
This fix adds the p2serial found in the api as another label.
> Fix for ipsec with multiple P2 using the same name

- Dockerfile
- Makefile
Docker building did not include version and git hashes.
> fix(docker): Add release information to Docker

- internal/config/main.go
- pkg/http/main.go
The format of the auth keys file was accidentally changed. Revert to the
old format.
Fixes #98
> fix(config): Revert config format change

- README.md
- internal/config/main.go
Use the basename of the configuration file we use by default in the Docker image.
This avoids this non-helpful error message when running without arguments:
```
[debian]$ ./fortigate-exporter.linux.amd64
2021/07/10 21:45:43 FortigateExporter 1.5.1-1-g9994480 ( 9994480 )
2021/07/10 21:45:43 Failed to read API authentication map file: open : no such file or directory
```
> feat(flag): Valid default for auth-file

- pkg/probe/bgp_neighbors.go
- pkg/probe/firewall_load_balance.go
- pkg/probe/firewall_load_balance_test.go
- pkg/probe/firewall_policy.go
- pkg/probe/license_status.go
- pkg/probe/probe.go
- pkg/probe/probe_test.go
- pkg/probe/system_available_certificates.go
- pkg/probe/system_ha_statistics.go
- pkg/probe/system_interface.go
- pkg/probe/system_link_monitor.go
- pkg/probe/system_resources_usage.go
- pkg/probe/system_status.go
- pkg/probe/virtual_wan_health_check.go
- pkg/probe/vpn_ipsec.go
- pkg/probe/vpn_ssl.go
This fixes a bunch of issues that we are running into regarding versions
and hammering on invalid authentication.
This also puts plumbing in place if we ever want to make more metadata available for other probe functions.
Finally, makes the probe return successful status if the metric is not supported due to version - that way the logs remain clean.
Fixes #112
Fixes #59
Before:
```
Jul 03 08:28:51 debian fortigate_exporter[34083]: 2021/07/03 08:28:51 Error: Get "https://fw-ftg-test.xxx.local/api/v2/monitor/system/status": x509: certificate has expired or is not yet valid: current time 2021-07-03T08:28:51+02:00 is after 2021-06-11T20:45:01Z
Jul 03 08:28:52 debian fortigate_exporter[34083]: 2021/07/03 08:28:52 Error: Get "https://fw-ftg-test.xxx.local/api/v2/monitor/system/resource/usage?int …
```
> fix(api-test): Sanity-check API connection

- .github/workflows/go.yml
- .github/workflows/release.yml
- Makefile
- go.sum
setup-env relies on that go install can install to $PATH. If users have
not configured their environment, using go run is easier on them.
> refactor(ci): Remove setup-env phase

- internal/config/main.go
This ensures that you can call config.Init() in tests that
otherwise have already called flag.Parse().
This was discovered as part of #115 where calling config.Init() in a test would not save `savedConfig`.
> refactor(config): Internal store as pointer

- README.md
- internal/config/main.go
- pkg/probe/probe.go
Hi,
First, thank you to all contributors for this great job. This exporter is helping us a lot every day.
I propose a capability to select only specific probes instead of all by default.
Objectives are:
- optimize scraping to only needed/interesting probes in order to save network and fortigate load
- optimize scraping at a large scale, when scraping large number of fortigate
- offer a solution to handle probing specificities for each fortios version in configuration file rather than in code  
- prevent continuous errors in logs about some probes failing
For example, I am getting a 403 for api/v2/monitor/firewall/load-balance on multiple fortios 6.0.10.
The code I propose use the configuration file to list probes to run for each fortigate.
There is 2 ways to add probes:
- by their name: …
> Add probe selection capability from configuration file

- internal/config/main.go
- pkg/probe/bgp_neighbor_routes_test.go
This will allow tests to re-initialize the config structure to apply any
calls to e.g. flag.Set() that may have happened.
At some point we should clean this up to not rely on global state
but rather pass in the config to the probe functions. But not today.
This will help #119
> refactor(config): Add re-init function for testing

- README.md
- internal/config/main.go
- pkg/probe/vpn_ssl.go
- pkg/probe/vpn_ssl_test.go
Hi,
We are interested in listing connected user to SSL VPN for example in Grafana dashboards.
This code add support for probing SSL VPN users in addition to other metrics.
The code also include a new parameter to limit number of retrieved users.
> feat(probe): Add probe for vpn SSL users

- README.md
- pkg/probe/probe.go
- pkg/probe/testdata/vpn-stats.jsonnet
- pkg/probe/vpn_ssl_stats.go
- pkg/probe/vpn_ssl_stats_test.go
Hi,
We are interested in listing connected user stats to SSL VPN for example in Grafana dashboards.
This code add support for probing SSL VPN stats.
> Add probe for vpn SSL stats

- README.md
Allows for granular permission granting according to selected category probe name.
Also fixing bad configuration or deprecated ones in the global monitor profile configuration.
> doc(readme): detail permissions per probe + update global monitor profile configuration

- README.md
- pkg/probe/probe.go
- pkg/probe/system_time.go
- pkg/probe/system_time_test.go
- pkg/probe/testdata/system-time.jsonnet
Hi,
This metric is interesting for detecting internal clock badly synchronized.
This NTP synchro status is not present in the API of old FortiOS, so there is no other way to monitor clock drift in this case (at least none I am aware of 😄 )
I limited the request to the root VDOM, as time is shared accross all VDOM.
For the metric type I have chosen to stay with Gauge. Counter could habe been a better choice, but I though some use case can break the always growing value:
- clock is resynchronized backward, then value will decrease
- firewall is restarted and start back with the default hour (if cell kipping time is dead for example)
- firewall is replaced by a new one after a failure. The new one can not be synchronized yet
> feat(probe): Add probe for fortigate internal clock time

- pkg/probe/probe.go
This PR improve Fortigate System/Time/clock probe timestamp accuracy.
When all probes are run and a lot of data is returned, processing can take up to 6 seconds.
Prometheus do integrates new metrics with timestamp corresponding to the time Prometheus makes the query to the exporter.
Therefore we have to process this probe as soon as possible in the code.
Required permissions to run this probe do not allow to run it instead of the status probe run first to determine the firewall connectivity. 
This PR simply move on top of the probe list the time probe.
> fix(probe): System/Time/Clock moved on top of probe list for better timestamp accuracy

- CONTRIBUTING.md
This is just a draft for CONTRIBUTING.md.
I had to start somewhere and Prometheus project CONTRIBUTING.md sounds like a good starting point to me.
I hope they will not take it bad :) we are kind of a child project to them, I guess they will be happy of the reuse.
Cleaned up sone things that do not seems interesting to talk about (this is just my point of view).
Feel free to add/remove anything this is just a starting point.
> doc(CONTRIBUTING.md): Add contributing page to the project

- Dockerfile
Fixes #155.
We used to not rely on Dockerhub because quay had issues pulling from it back in the days. I'll gamble that those issues have been resolved these days.
> fix(arm64): Revert back to using Dockerhub

- pkg/probe/wifi_ap_status.go
Apparently pagination does not work on newer FortiOS on this particular
API call. It seems unlikely that somebody with more than 1000 APs would
complain about large API calls, so remove the limit for now.
Fixes #163
> fix(wifi_ap_status): Fix for FortiOS 7.0

- README.md
- pkg/probe/probe.go
- pkg/probe/system_sdn_connector.go
- pkg/probe/system_sdn_connector_test.go
- pkg/probe/testdata/system-sdn-connector.jsonnet
This implements a feature that is important for us, querying the SDN Connectors for status (https://github.com/bluecmd/fortigate_exporter/issues/209) . We have many policies based on an assumption that the learned address lists from our connectors (especially AWS) are happy and up-to-date.
> feat(probe): status of SDN Connectors

- README.md
- pkg/probe/firewall_ippool.go
- pkg/probe/firewall_ippool_test.go
- pkg/probe/probe.go
- pkg/probe/testdata/fw-ippool.jsonnet
This merge adds support for ippool information. This closes #231
> feat(probe): support for ippool info

- README.md
- go.sum
- pkg/probe/ospf_neighbors.go
- pkg/probe/ospf_neighbors_test.go
- pkg/probe/probe.go
- pkg/probe/testdata/router-ospf-neighbors.jsonnet
Added new metric for OSPF neighbors per VDOM.
API uri query: api/v2/monitor/router/ospf/neighbors?vdom=*
resolves #242
reviewer @bluecmd
> feat: added OSPF metrics and corresponding testcase

- pkg/probe/ospf_neighbors.go
- pkg/probe/ospf_neighbors_test.go
- pkg/probe/testdata/router-ospf-neighbors.jsonnet
Hi @bluecmd !
Spotted a small issue in the OSPF code state returned, it appears to be shifted by 1 for each value.
Let me know if somethings not right. I assumed that the wanted value for the test was 8 (Full).
Benjamin
> fix(probe): correct OSPF state enum

- README.md
- pkg/probe/firewall_ippool.go
- pkg/probe/firewall_ippool_test.go
Hello,
a while ago I added the ippool probe to the exporter. While using this we noticed that it is hard to see if an ip pool is exhausted if you are mix and matching one-to-one and pba ip pools. 
Unfortunately the api does not return the ippool type but it does return the amount of pba_per_ip which is 1 for a one-to-one and x for port-block-allocation. This way we can kind of differentiate the types being in use and we can create reasonable alerts: 
`fortigate_ippool_available_ratio < 0.2 and fortigate_ippool_pba_per_ip != 1`
Also it seems like overload ippools are not being returned by the API (which I have just noticed now).
> feat: Added pba_per_ip return for ippool to differentiate between ippool types
