- Dockerfile
- README.md
- docker-compose.yml
Added a Dockerfile as well as a docker-compose file. Thanks for the great work on this project!
> Create Docker File

- README.md
Add some documentation of the CLI parameters
> chore(README): add documentation for cli parameters

- README.md
- probe.go
- probe_test.go
- testdata/license-status.jsonnet
Metrics to monitor vdom license usage. Should be possible to add other license statuses as well.
> Add License metrics

- README.md
Adding additional configuration on docker-compose for applying multiple parameter
>  Update README.md on docker-compose section

- probe.go
- probe_test.go
- testdata/link-monitor-error.jsonnet
- testdata/link-monitor-unknown.jsonnet
> Change link monitor status to label based values

- README.md
Make it clearer that the exporter works fine with multiple targets.
This was asked here: https://www.reddit.com/r/fortinet/comments/llwqab/fortigate_exporter_for_prometheus/gns2iqv/
> Update Prometheus configuration example

- probe.go
- probe_test.go
- testdata/virtual_wan_health_check.jsonnet
closes #43 
Change encoding type from string to float64
> fix(probeVirtualWANPerf): change Array type from string to float64

- README.md
Add instructions how to get started using the automatic builds.
Ping #38
> doc: instructions for usage of CI

- .github/workflows/go.yml
- probe.go
> feat(Github Workflow): check if GO files are formatted

- .releaserc.yml
> feat(CI): Enable semantic-release

- .releaserc.yml
> fix(CI): remove target path of binary locations in .releaserc.yml

- .github/workflows/go.yml
- .github/workflows/release.yml
- go.mod
- go.sum
This PR upgrade the module and CI definitions to GO 1.16
> feat: upgrade to go 1.16

- .github/workflows/go.yml
- .github/workflows/release.yml
- .releaserc.yml
- Makefile
- fortigate_exporter.go
> feat: Implement versioning and add Makefile

- README.md
Boolean flags behave a bit differently.
Fixes #126
> doc(readme): Update how the -insecure flag works

- README.md
Add a chat room for discussions
> doc(readme): Matrix chat room

- .gitignore
- Makefile
Context:  https://github.com/bluecmd/fortigate_exporter/pull/142#issuecomment-912801357
> ci(Makefile): add coverage report and run additional tests

- README.md
Update readme.md with example how to use prometheues configuration as per user local enviromnent
> doc(readme): Elaborate which parts are user specified

- .github/semantic.yml
Target our own documentation for PR issues
> ci(pr): Create semantic.yml

- README.md
In order to complete the Apache 2.0 re-license process, remove the contribtion of @faizan-syed.
* Original: https://github.com/bluecmd/fortigate_exporter/pull/221
* Re-License: https://github.com/bluecmd/fortigate_exporter/pull/309
> chore: Remove contributions by @faizan-syed

- LICENSE
In order for this project to be adopted by the Prometheus Community update the license to Apache Version 2.0.
> chore: Change project license
